// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4H_XdeKBmh86wWavK5iDFPUO2dEW4tj4',
    appId: '1:45194823507:web:2974479b7cf16e35ac03a6',
    messagingSenderId: '45194823507',
    projectId: 'test-analytics-126f5',
    authDomain: 'test-analytics-126f5.firebaseapp.com',
    storageBucket: 'test-analytics-126f5.appspot.com',
    measurementId: 'G-423ZMS4DTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK51L1JNwyXpwoeAD61E3ZpHg-GTb_7e8',
    appId: '1:45194823507:android:f096f9f874c65da3ac03a6',
    messagingSenderId: '45194823507',
    projectId: 'test-analytics-126f5',
    storageBucket: 'test-analytics-126f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhhT4He0TY4WvgrtME-O9taJafqMlLfg',
    appId: '1:45194823507:ios:192e9a37294acbc4ac03a6',
    messagingSenderId: '45194823507',
    projectId: 'test-analytics-126f5',
    storageBucket: 'test-analytics-126f5.appspot.com',
    iosBundleId: 'com.example.testFirebaseAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVhhT4He0TY4WvgrtME-O9taJafqMlLfg',
    appId: '1:45194823507:ios:192e9a37294acbc4ac03a6',
    messagingSenderId: '45194823507',
    projectId: 'test-analytics-126f5',
    storageBucket: 'test-analytics-126f5.appspot.com',
    iosBundleId: 'com.example.testFirebaseAnalytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4H_XdeKBmh86wWavK5iDFPUO2dEW4tj4',
    appId: '1:45194823507:web:551608af69231c21ac03a6',
    messagingSenderId: '45194823507',
    projectId: 'test-analytics-126f5',
    authDomain: 'test-analytics-126f5.firebaseapp.com',
    storageBucket: 'test-analytics-126f5.appspot.com',
    measurementId: 'G-3942YZ1TBE',
  );
}
